# NOTE: update this with your service name
service: serverless-typescript-boilerplate

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline # Enables offile run
  - serverless-dotenv-plugin # Load .env as environment variables

custom:
  myStage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  
  # To load environment variables externally
  environment:
    SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}
    MESSAGE: ${self:custom.myStage}

functions:
  mirror:
    handler: api/mirror.main
    events:
      - http:
          path: mirror
          method: get
      - http:
          path: mirror
          method: put
  user:
    handler: api/user/handler.get
    events:
      - http:
          path: user/{id}
          method: get