service: db

plugins:
  - serverless-dynamodb-local

custom:
  dynamodb:
    stages:
      - ${opt:stage, self:provider.stage}
  stage: ${opt:stage, self:provider.stage}

  # Set our DynamoDB throughput for prod and all other non-prod stages.
  # Set the table name here so we can use it while testing locally
  testTableName: ${self:custom.stage}-test

  tableThroughputs:
    prod: 1
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

resources:
  Resources:
    TestTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.testTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.tableThroughput}
          WriteCapacityUnits: ${self:custom.tableThroughput}
  Outputs:
    TestTableArn:
      Value:
        Fn::GetAtt:
          - TestTable
          - Arn
      Export:
        Name: ${self:custom.stage}-TestTableArn
