service: db

plugins:
  - serverless-dynamodb-local

custom:
  stage: ${opt:stage, self:provider.stage}

  # Set our DynamoDB throughput for prod and all other non-prod stages.
  # Set the table name here so we can use it while testing locally
  testTableName: ${self:custom.stage}-test

  # Set our DynamoDB throughput for prod and all other non-prod stages.
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
  DeletionPolicies:
    prod: Retain
    default: Delete
  DeletionPolicy: ${self:custom.DeletionPolicies.${self:custom.stage}, self:custom.DeletionPolicies.default}

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-central-1

resources:
  Resources:
    TestTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.testTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
  Outputs:
    TestTableArn:
      Value:
        Fn::GetAtt:
          - TestTable
          - Arn
      Export:
        Name: ${self:custom.stage}-TestTableArn
